Blog/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "Article"

urlpatterns = [
    path('',views.articles,name = "articles"),
    path('dashboard/',views.dashboard,name = "dashboard"),
    path('admindashboard/',views.admindashboard,name = "admindashboard"),
    path('generaladmin/',views.adminarticles,name = "adminarticles"),
    path('addarticle/',views.addArticle,name = "addarticle"),
    path('article/<int:id>/',views.detail,name = "detail"),
    path('update/<int:id>/',views.updateArticle,name = "update"),
    path('delete/<int:id>/',views.deleteArticle,name = "delete"),
    path('comment/<int:id>/',views.addComment,name = "comment"),
    
    
    
    
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myblog/urls.py
from django.contrib import admin
from django.urls import path,include
from Blog import views
from sitemap import sitemapviews
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve 
from django.contrib.auth import views as auth_views

app_name = "index"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',sitemapviews.index,name = "index"),
    path('about/',sitemapviews.about,name="about"),
    path('contact/',sitemapviews.contact,name="contact"),
    path('user/',include("user.urls")),
    path('articles/',include("Blog.urls")),
    path('category/',views.categorydetail,name = "category"),
    
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/about.html
{% extends "layout.html" %}
{% load static %}
{% block body %}


<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Seçkin Özer | Hakkında">
  <meta name="keywords" content="Seçkin , ÖZER , Blog">
  <link rel="stylesheet" href=" {% static 'css/about.css' %} ">
  <title>Hakkımda | Seçkin Özer</title>
</head>
<body>       
    <section  class="about">
            <div class="container" >

                <section class="team section custom ">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-4 col-sm-6 col-xs-12">
                                <div class="team-item wow fadeInLeft" data-wow-duration="1.6s">
                                    <figure>
                                        <img src="../static/img/seckin.png"   alt="">
                                        <figcaption>
                                            <div class="info">
                                                <h3>Seçkin Şevki Özer</h3>
                                                <p>Girişimci | Software Developer</p>
                                            </div>
                                            
                                            <div class="social">
                                                <a href="https://twitter.com/seckinozer0" class="twitter" data-abc="true"><i class="bi bi-twitter"></i></a>
                                                <a href="https://www.instagram.com/seckinozer0/" class="instagram" data-abc="true"><i class="bi bi-instagram"></i></a>
                                                <a href="https://www.linkedin.com/in/seçkin-şevki-özer-302376181/" class="linked-in" data-abc="true"><i class="bi bi-linkedin"></i></a>
                                                
                                            </div>
                                            
                                        </figcaption>
                                        
                                    </figure>
                                    
                                </div>
                                
                            </div>
                            
                            <div class="col-md-4 col-sm-6 col-xs-12">
                                <div class="team-item " style="width: 175% ;" data-wow-duration="1.6s">
                                    <figure>
                                        <br><br><br><br>
                                        <div class="" >
                                            
                                            <div class="typing-demo">
                                                <h2 class="title-overview text-white " style="float: left;" >Kişisel Bloğuma Hoşgeldiniz<hr style="background: #fff;" > </h2>
                                            </div>
                                            <p class="subtitle-overview wow fadeInLeft text-white" style = "float: left; font-size:17.5px;" data-wow-duration="1.6s"> Herkese Merahaba, <br> 
                                                Öncelikle blogumu ziyaret ettiğiniz için teşekkür ederim. Ben Seçkin Şevki Özer Erciyes Üniversitesi Mekatronik Mühendisliği 3. Sınıf öğrencisiyim.Bu Blogu temel mühendislik bilimleri , programlama ve yazılım öğrenmek isteyenlerin uğrak noktası olması ve aynı zamanda Türkiye'de mühendislik, programlama ve yazılım bilimlerinin yükselmesine katkı sunmak amacıyla; yazılım , tasarım , elektronik ve sosyal alanlardaki bilgi ve deneyimlerimi sizin ile paylaşmak için kurdum.
                                            </p>
                                            <p class="subtitle-overview wow fadeInLeft text-white" style = "float: left; font-size:17.5px;" data-wow-duration="1.6s"> 
                                                Birlikte yazmaya, öğrenmeye , hata almaya ve çözmeye var mısınız? Haydi o zaman teknolojiyi baştan yazmaya başlayalım.
                                            </p>
                                        </div>
                                    </figure>
                                </div>
                            </div>
                        
                        </div>
                    </div>
                </section>        
                </div>

            </div>
            
    </section>
</body>
</html>
    
    
{% endblock %}

templates/addarticle.html
{% extends "layout.html" %}
{% load static %}
{% block body %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href=" {% static 'css/articles.css' %} ">
  <title>Bir Makale Ekleyin</title>
</head>
<body>
      <script>
        $(document).ready(function() {
          $('#dataTable').DataTable();
        });
      </script>
      <section class="d-flex align-items-center hero">
        <div class="container text-center position-relative wow fadeInLeft" data-wow-duration="1.2s" >
          <h1 >Bir Yazı Paylaşın</h1>
        </div>
      </section>
      <br>
      <div class="container">
          <form method = "post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-success">Makale Ekle</button>
          </form>
      </div>
      
           
</body>
</html>  
      
      
        
  
    
 
{% endblock body %}

templates/articles.html
{% extends "layout.html" %}
{% load static %}
{% block body %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Seçkin Özer | Hakkında">
  <meta name="keywords" content="Seçkin , ÖZER , Blog">
  <link rel="stylesheet" href=" {% static 'css/articles.css' %} ">
  <link rel="stylesheet" href=" {% static 'css/detail.css' %} ">
  <title>Blog</title>
</head>
<body>
  <section class="d-flex align-items-center hero">
    <div class="container position-relative wow fadeInLeft" data-wow-duration="1.2s" >
      <h1>KİŞİSEL BLOĞUMA HOŞGELDİNİZ</h1>
    </div>
  </section>
  <section>
    
    <div class="container" >
      <section class="breadcrumbs wow fadeInLeft" data-wow-duration="1.2s" >
        <div class="container">
    
          <div class="d-flex justify-content-between align-items-center">
            <ol>
              <li><a href="/articles">Tüm Kategoriler</a></li>
              {% for category in categories  %}
                    <li><a href="/category/?category={{category.id}}">{{category.name}}</a></li>
                {% endfor %}
            </ol>
          </div>
    
        </div>
      </section><!-- End Blog Section -->
      <div class="row">
        
      {% if articles %}
        <!-- Blog Entries Column -->
        <div class="col-md-8 wow fadeInLeft" data-wow-duration ="1.5s">
         <br>
         {% for article in articles %}
          <!-- Blog Post -->
          <div class="card mb-4">
            {% if article.article_image %}
              <img class="card-img-top "  src="{{article.article_image.url }}" alt="Card image cap">
            {% else %}
              <img class="card-img-top" src=" ../static/img/none.jpg " alt="bu makalede resim yok">
            {% endif %}
            
            <div class="card-body">
              <h2 class="card-title"><a href="{% url 'Article:detail' article.id %}">{{article.title}}</a> </h2>
              <hr>
              <p class="card-text">{{article.content|safe|truncatewords:50}}</p>
              <a href="{% url 'Article:detail' article.id %}" class="btn btn-primary">Devamını Oku →</a>
            </div>
            <div class="card-footer text-muted">
              Yayınlayan :<a href="/about"> @{{article.author.username}}</a>
               |
              Kategori :<a href="">{{article.category}}</a>
              |
              Yayınlanma Tarihi : {{article.created_date}}
            </div>
          </div>
          {% endfor %}
        </div>
        <div class="col-lg-4">
          <div class="sidebar wow fadeInRight" data-wow-duration="1.5">
            <h3 class="sidebar-title"> Diğer Yazılar</h3>
            {% if articles %}
              {% for article in articles  %}
              <div class="sidebar-item recent-posts">
                <div class="post-item clearfix">
                  <img src="{{article.article_image.url }}" alt="Makale resmi">
                  <h4 class="text-success"><a href="{% url 'Article:detail' article.id %}"> {{article.title}} </a></h4>
                  <time datetime="2020-01-01"> {{article.created_date}} </time>
                  <a  style="float: right;" href="{% url 'Article:detail' article.id %}"> Devamını Oku</a>
                </div>
                <hr>
              </div>
              {% endfor %}
            
            {% endif %}
          </div>
          <div class="sidebar wow fadeInRight" data-wow-duration="1.5">
            
            <h3 class="sidebar-title"> Seçkin Şevki Özer</h3>
              <div class="sidebar-item recent-posts">
                <div class="post-item clearfix">
                  <img src="{% static 'img/seckin.png' %} " alt="Makale resmi">
                  
                  <h4 class="">
                    <ul>
                      <li>Erciyes Üniversitesi Mekatronik Mühendisliği 3. Sınıf </li>
                      <li>Software Developer</li>
                      <li>Founder of TARA Asistan</li>
                    </ul>
                    </h4>
                  <a  style="float: right;" href="/about/"> Devamını Oku</a>
                </div>
                <hr>
              </div>
          </div>
        </div>
          {% else %}
          <div class="alert alert-danger">
            Henüz Böyle Bir Makale Bulunmuyor
          </div>
          {% endif %}
      </div>
      <!-- /.row -->
  
    </div>
    
  </section>
  
      
</body>
</html>

{% endblock  %}

templates/category.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}



<script>
  $(document).ready(function() {
    $('#dataTable').DataTable();
  });
  
</script>
<title>Kurslar</title>
<link href="../static/css/style.css" rel="stylesheet" />
<div class="sb-nav-fixed"> 
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                
                {% if articles %}
                <div class="card mb-4">
                    <div class="card-header">
                        <i class="fa fa-table mr-1"></i>
                        Paylaşılan Yazılar
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                    <tr>
                                    <th>Makale Adı</th>
                                    <th>İD</th>
                                    <th>Kategori</th>
                                    <th>Makale İçeriği</th>
                                    <th>Yayınlanma Tarihi</th>
                                    <th>Düzenle</th>
                                    </tr>
                                </thead>
                                
                                <tbody>
                                    {% for article in articles  %}
                                    <tr>
                                        <td><a href="/articles/article/{{article.id}}">{{article.title}}</a> </td>
                                        <td> {{article.id}} </td>
                                        <td> {{article.category}} </td>
                                        <td>{{article.content|safe|truncatewords:15}}</td>
                                        <td> {{article.created_date}} </td>
                                        <td><a class="btn btn-primary " href="/articles/article/{{article.id}}">Devamını Oku</a></td>  
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                {% else %}

                <div class ="row">

                    <div class="col-md-10 offset-md-3">
                        <div class="col-lg-8">
                <div class = "alert alert-danger">
                    Bu Kategori Altında Herhangi Bir Makale Bulunamadı...
                </div>
                </div>
                </div>
                </div>
                {% endif %}
                <hr>
            </div>
        </main>
        
    
    </div>
</div>
{% endblock body %}

templates/contact.html
{% extends "layout.html" %}
{% load static %}
{% block body %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Seçkin Özer Benimle İletişime Geçin">
  <meta name="keywords" content="Seçkin ">
  <link rel="stylesheet" href=" {% static 'css/contact.css' %} ">
  <title>Benimle İletişime Geçin</title>
</head>
<body>
  <section class="d-flex align-items-center hero">
    <div class="container position-relative" >
        <div class="container contact-form">
            <div class="row ">
              <div class="col-lg-8 col-lg-offset-2">
                <form id="contact-form" method="post" action="" role="form">
                {% csrf_token %}
                <div class="messages"></div>
                <div class="highline">
                    <h3>İletişim</h3>
                </div>
                <hr style="margin-left: 350px; background:white;">
                <div class="controls">
                  <div class="row">
                    <div class="col-md-6">
                      <div class="form-group">
                        <label for="form_name">İsim Soyisim*</label>
                        <input id="form_name" type="text" name="support_name" class="form-control" placeholder="İsim Soyisim *" required="required" data-error="Firstname is required.">
                        <div class="help-block with-errors"></div>
                      </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                          <label for="form_email">E-Posta *</label>
                          <input id="form_email" type="email" name="support_email" class="form-control" placeholder="Lütfen Geçerli Bir E-Posta Giriniz *" required="required" data-error="Valid email is required.">
                          <div class="help-block with-errors"></div>
                        </div>
                      </div>
                  </div>
                  <div class="row" >
                    <div class="col-md-6">
                        <div class="form-group">
                          <label for="form_email">Telefon Numarası *</label>
                          <input id="form_email" type="text" name="support_phone" class="form-control" placeholder="Lütfen Geçerli Bir Telefon Numarası Giriniz *" required="required" data-error="Valid email is required.">
                          <div class="help-block with-errors"></div>
                        </div>
                      </div>
                  </div>
                  <div class="row">
                    <div class="col-md-12">
                      <div class="form-group">
                        <label for="form_message">Mesajınız *</label>
                        <textarea id="form_message" name="support_content" class="form-control" placeholder="Lütfen Mesajınızı Giriniz *" rows="4" required data-error="Please,leave us a message."></textarea>
                        <div class="help-block with-errors"></div>
                      </div>
                    </div>
                    <div class="col-md-12">
                      <input type="submit" class="btn btn-success btn-send" value="Gönder">
                    </div>
                  </div>       
                </div>
                </form>
                <div class="underline">
                    <h6> blog.seckinozer@gmail.com</i></h6>
                </div>
              </div>     
            </div>
          </div>
    </div>
  </section>
  <footer>
    <div class="footermenu">
        <div class="label">Referanslar</div>
        <div class="spacer"></div>
        <div class="item"><a style="text-decoration:none" class="text-white" href="https://reezoteknoloji.pythonanywhere.com"> <i class="bi bi-bookmarks"> REEZO Teknoloji</i> </a></div>
        <div class="item"><a style="text-decoration:none" class="text-white" href="https://reezoteknoloji.pythonanywhere.com/service/taraasistan"><i class="bi bi-bookmarks"> TARA Asistan</i> </div>
        <div class="item"><a style="text-decoration:none" class="text-white" href="https://www.instagram.com/seckinozer0/"><i class="bi bi-instagram"> @seckinozer0</i></div>
        <div class="item"><a style="text-decoration:none" class="text-white" href="https://twitter.com/seckinozer0"><i class="bi bi-twitter"> @seckinozer0</i></div>
        <div class="item"><a style="text-decoration:none" class="text-white" href="https://www.linkedin.com/in/seçkin-şevki-özer-302376181/"><i class="bi bi-linkedin"> Seçkin Şevki Özer</i></div>
        <div class="item"><a style="text-decoration:wavy" class="text-white" href="https://github.com/Seckinozer01"><i class="bi bi-github"> Seçkin Şevki Özer</i></div>
      </div>
  </footer>
</body>
</html>
{% endblock body %}

templates/detail.html
{% extends "layout.html" %}
{% load static %}
{% block body %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title> {{article.title}} </title>
  <link rel="stylesheet" href=" {% static 'css/detail.css' %} ">
</head>
<body>
  <style>
    .hero {
      width: 100%;
      height: 50vh;
      background: url(" {% static 'img/main.jpg' %} ") top center;
      background-size: cover;
      position: relative;
    }
  </style>
<section class="d-flex align-items-center hero">
  <div class="container position-relative wow fadeInLeft" data-wow-duration="1.2s" >
    <h1 class="text-white" > {{article.title}} </h1>
  </div>
</section>
  <section class="breadcrumbs wow fadeInLeft" data-wow-duration="1.2s" >
    <div class="container">
      <div class="d-flex justify-content-between align-items-center">
        <ol>
          <li><a href="/articles">Blog</a></li>
          <li><a href="/category/?category={{category.id}}"> {{article.category}} </a></li>
          <li> {{article.title}} </li>
        </ol>
      </div>
    </div>
  </section><!-- End Blog Section -->
  
  <div class="container ">
    <div class="row">
      <div class="col-lg-8 post-detail wow fadeInLeft" data-wow-duration ="1.5s" >
        <div class="md-4" style="float: left;">
          <p class="lead md-4"> 
            <a href="#">{{article.author.username}}</a> tarafından yayınlandı
          </p>
        </div>
        <div style=" float:right">
          <p class="lead">Paylaşım Tarihi : {{article.created_date}}</p>
        </div>
        {% if article.article_image %}
        <img class="img-fluid rounded" src="{{article.article_image.url }}" alt="">
        {% endif %}
        <hr>
        <p class="lead">{{article.content|safe}}</p>
        <hr>
        {% if article.category.name == "Python" %}
        <h3>python</h3>
        {% else %}
        <h3>başka</h3>
        {% endif %}
        <div class="card mb-3 wow fadeIn">
          <div class="card-header font-weight-bold">Bu Makaleye Bir Yorum Ekleyin</div>
          <div class="card-body">
              <form method="post" action="{% url 'Article:comment' article.id %}">  
                {% if request.user.is_authenticated %}
                {% csrf_token %}
                  <!-- Comment -->
                  <div class="text-muted"> {{ request.user.username}} olarak yorum yapıyorsunuz. </div>
                  <br>
                  <div class="form-group">
                      <textarea class="form-control" id="replyFormComment" name="comment_content" rows="5" required placeholder="Yorumunuz" ></textarea>
                  </div>
                  <div class="text-center mt-4">
                    <button class="btn btn-info btn-md" style="width: 100%;" type="submit">Paylaş</button>
                  </div>         
                {% else %}
                <div class="alert alert-danger"> Yorum Eklemek İçin Lütfen <a href="/user/login"> Giriş Yapın.</a></div>
                {% endif %}         
              </form>
          </div>
        </div>
        <!--/.Reply-->
        {% if comments %}
        <!--Comments-->
            <div class="card card-comments mb-3 wow fadeIn">
                
                  <div class="card-body">
                    {% for comment in comments  %}
                    <div class="media d-block d-md-flex mt-4">
                      <div class="media-body text-center text-md-left ml-md-3 ml-0">
                        <hr>
                            <h5 class="mt-0 font-weight-bold">{{comment.comment_author}}
                              <small>{{comment.comment_date}} Tarihinde Yayınlandı</small>
                                <a href="" class="pull-right">
                                    <i class="fa fa-reply"></i>
                                </a>
                            </h5>
                            {{comment.comment_content}}
                        </div>
                    </div>
                    <hr>
                    {% endfor %}
                  </div>
            </div>
          {% else %}
            <div class="alert alert-danger">Bu Makalede Herhangi Bir Yorum Yok.</div>
          {% endif %}
      </div>
      <div class="col-lg-4">
        <div class="sidebar wow fadeInRight" data-wow-duration="1.5">
          <h3 class="sidebar-title"> Kategoriler </h3>
          {% if categories %}
            {% for category in categories  %}
              <li><a href="?category={{category.id}}">{{category.name}}</a></li>
            {% endfor %}
          {% endif %}
          <hr>
          <h3 class="sidebar-title"> Diğer Yazılar</h3>
          {% if articles %}
            {% for article in articles  %}
            <div class="sidebar-item recent-posts">
              <div class="post-item clearfix">
                <img src="{{article.article_image.url }}" alt="Makale resmi">
                <h4 class="text-success"><a href="{% url 'Article:detail' article.id %}"> {{article.title}} </a></h4>
                <time datetime="2020-01-01"> {{article.created_date}} </time>
                <a  style="float: right;" href="{% url 'Article:detail' article.id %}"> Devamını Oku</a>
              </div>
              <hr>
            </div>
            {% endfor %}
          
          {% endif %}
        </div>
        <div class="sidebar wow fadeInRight" data-wow-duration="1.5"> 
          <h3 class="sidebar-title"> Seçkin Şevki Özer</h3>
            <div class="sidebar-item recent-posts">
              <div class="post-item clearfix">
                <img src="{% static 'img/seckin.png' %} " alt="Makale resmi">
                
                <h4 class="">
                  <ul>
                    <li>Erciyes Üniversitesi Mekatronik Mühendisliği 3. Sınıf </li>
                    <li>Software Developer</li>
                    <li>Founder of TARA Asistan</li>
                  </ul>
                  </h4>
                <a  style="float: right;" href="/about/"> Devamını Oku</a>
              </div>
              <hr>
            </div>
        </div>
      </div>
    </div>
    </div>
  </div>
</body>
</html>

{% endblock body %}

templates/index.html
{% extends "layout.html" %}
{% load static %}

{% block body %}


<style>
  

.hero {
  width: 100%;
  height: 100vh;
  background: url("../static/img/hero-bg.jpg") top center;
  background-size: cover;
  position: relative;
}

.hero:before {
  content: "";
  background: rgba(0, 0, 0, 0.5);
  position: absolute;
  bottom: 0;
  top: 0;
  left: 0;
  right: 0;
}

.hero .container {
  padding-top: 70px;
}

.hero h1 {
  margin: 0 0 10px 0;
  font-size: 48px;
  font-weight: 700;
  line-height: 56px;
  text-transform: uppercase;
  color: #fff;
}

.hero h2 {
  color: #eee;
  margin-bottom: 30px;
  font-size: 24px;
}

.hero .btn-get-started {
  font-family: "Raleway", sans-serif;
  text-transform: uppercase;
  font-weight: 500;
  font-size: 14px;
  letter-spacing: 0.5px;
  display: inline-block;
  padding: 10px 28px;
  transition: 0.5s;
  border: 2px solid #fff;
  color: #fff;
}

.hero .btn-get-started:hover {
  background: #1628cc;
  border-color: #1628cc;
}

</style>
<style>
    


  .footermenu {
      text-transform: uppercase;
      color: rgba(255, 255, 255, 0.8);
      display: inline-block;
      cursor: pointer;
      pointer-events: none;
      position: absolute;
      bottom: 20px;
      left: 20px;
  }
  .footermenu:hover {
      pointer-events: all;
    }
  
  .label {
    display: inline-block;
    cursor: pointer;
    pointer-events: all;
  }
  .spacer {
    display: inline-block;
    width: 80px;
    margin-left: 15px;
    margin-right: 15px;
    vertical-align: middle;
    cursor: pointer;
    position: relative;
  }
  .spacer:before {
    content: "";
    position: absolute;
    border-bottom: 1px solid #ffffff;
    height: 1px;
    width: 0%;
    transition: width 0.25s ease;
    transition-delay: 0.7s;
  }
  .item {
    position: relative;
    display: inline-block;
    margin-right: 30px;
    top: 10px;
    opacity: 0;
    transition: opacity 0.5s ease, top 0.5s ease;
    transition-delay: 0;
  }
  .item a:before {
      content: "";
      position: absolute;
      width: 100%;
      height: 2px;
      bottom: -6px;
      left: 0;
      background-color: #1768ff96;
      visibility: hidden;
      width: 0px;
      transition: all 0.3s ease-in-out 0s;
    }
  span {
    transition: color 0.5s ease;
  }
  .item:hover span {
    color: #ff0000;
  }
  .menu:hover .spacer:before {
    width: 100%;
    transition-delay: 0s;
  }
  .footermenu:hover .item {
    opacity: 1;
    top: 0px;
  }
  .item:nth-child(1) {
    transition-delay: 0.45s;
  }
  .item:nth-child(2) {
    transition-delay: 0.4s;
  }
  .item:nth-child(3) {
    transition-delay: 0.35s;
  }
  .item:nth-child(4) {
    transition-delay: 0.3s;
  }
  .item:nth-child(5) {
    transition-delay: 0.25s;
  }
  .item:nth-child(6) {
    transition-delay: 0.2s;
  }
  .item:nth-child(7) {
    transition-delay: 0.15s;
  }
  .item:nth-child(8) {
    transition-delay: 0.1s;
  }
  .item:nth-child(9) {
    transition-delay: 0.05s;
  }
  .item:nth-child(10) {
    transition-delay: 0s;
  }
  .footermenu:hover .item:nth-child(1) {
    transition-delay: 0.25s;
  }
  .footermenu:hover .item:nth-child(2) {
    transition-delay: 0.3s;
  }
  .footermenu:hover .item:nth-child(3) {
    transition-delay: 0.35s;
  }
  .footermenu:hover .item:nth-child(4) {
    transition-delay: 0.4s;
  }
  .footermenu:hover .item:nth-child(5) {
    transition-delay: 0.45s;
  }
  .footermenu:hover .item:nth-child(6) {
    transition-delay: 0.5s;
  }
  .footermenu:hover .item:nth-child(7) {
    transition-delay: 0.55s;
  }
  .footermenu:hover .item:nth-child(8) {
    transition-delay: 0.6s;
  }
  .footermenu:hover .item:nth-child(9) {
    transition-delay: 0.65s;
  }
  .footermenu:hover .item:nth-child(10) {
    transition-delay: 0.7s;
  }
  </style>

<section class="d-flex align-items-center hero" >
  <div class="container position-relative wow fadeInLeft " data-wow-duration="1.5s" >
    <h1> KİŞİSEL BLOĞUMA HOŞGELDİNİZ</h1>
    <h2>Haydi geleceği birlikte yazalım</h2>
    <a href="/articles" class="btn-get-started scrollto">Başlayın</a>
  </div>
</section>
<footer>
  <div class="footermenu">
      <div class="label">Referanslar</div>
      <div class="spacer"></div>
      <div class="item"><a style="text-decoration:none" class="text-white" href="https://reezoteknoloji.pythonanywhere.com"> <i class="bi bi-bookmarks"> REEZO Teknoloji</i> </a></div>
      <div class="item"><a style="text-decoration:none" class="text-white" href="https://reezoteknoloji.pythonanywhere.com/service/taraasistan"><i class="bi bi-bookmarks"> TARA Asistan</i> </div>
      <div class="item"><a style="text-decoration:none" class="text-white" href="https://www.instagram.com/seckinozer0/"><i class="bi bi-instagram"> @seckinozer0</i></div>
      <div class="item"><a style="text-decoration:none" class="text-white" href="https://twitter.com/seckinozer0"><i class="bi bi-twitter"> @seckinozer0</i></div>
      <div class="item"><a style="text-decoration:none" class="text-white" href="https://www.linkedin.com/in/seçkin-şevki-özer-302376181/"><i class="bi bi-linkedin"> Seçkin Şevki Özer</i></div>
      <div class="item"><a style="text-decoration:wavy" class="text-white" href="https://github.com/Seckinozer01"><i class="bi bi-github"> Seçkin Şevki Özer</i></div>
    </div>
</footer>

<!-- End Hero -->
<a href="#" class="back-to-top"  ><i class="fa fa-arrow-up"></i></a>

<!-- Vendor JS Files -->
<script src="../static/js/jquery.min.js"></script>
<script src="../static/js/bootstrap.bundle.min.js"></script>
<script src="../static/js/jquery.easing.min.js"></script>


<!-- Template Main JS File -->





{% endblock body %}